apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dnd-ingress
  namespace: dnd
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /dnd
            pathType: Prefix
            backend:
              service:
                name: dnd-website-service
                port:
                  number: 80
          - path: /dnd_api
            pathType: Prefix
            backend:
              service:
                name: dnd-api-service
                port:
                  number: 80
