name: Build and Push Docker Images

# on:
#   release:
#     types:
#       - published
on:
    push:
      branches:
        - main

jobs:
  build-and-push:
    name: Build and Push Docker Images to DockerHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set up Docker tags
      id: set-tags
      run: |
        # Extract the release version, removing the "v" prefix if it exists
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "TAGS=latest,${VERSION}" >> $GITHUB_ENV

    - name: Build and push dnd_website image
      run: |
        docker build -t dlots/dnd_website:${VERSION} -t dlots/dnd_website:latest -f website/Dockerfile .
        docker push dlots/dnd_website:${VERSION}
        docker push dlots/dnd_website:latest

    - name: Build and push dnd_api image
      run: |
        docker build -t dlots/dnd_api:${VERSION} -t dlots/dnd_api:latest -f town_builder/Dockerfile .
        docker push dlots/dnd_api:${VERSION}
        docker push dlots/dnd_api:latest
